/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/linode/provider-linode/apis/instance/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Image.
func (mg *Image) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.DiskID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.DiskIDRef,
		Selector:     mg.Spec.ForProvider.DiskIDSelector,
		To: reference.To{
			List:    &v1alpha1.DiskList{},
			Managed: &v1alpha1.Disk{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DiskID")
	}
	mg.Spec.ForProvider.DiskID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DiskIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.LinodeID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.LinodeIDRef,
		Selector:     mg.Spec.ForProvider.LinodeIDSelector,
		To: reference.To{
			List:    &v1alpha1.InstanceList{},
			Managed: &v1alpha1.Instance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.LinodeID")
	}
	mg.Spec.ForProvider.LinodeID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.LinodeIDRef = rsp.ResolvedReference

	return nil
}
