apiVersion: ipv6.linode.upbound.io/v1alpha1
kind: IPv6Range
metadata:
  annotations:
    meta.upbound.io/example-id: ipv6/v1alpha1/ipv6range
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    linodeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foobar
    prefixLength: 64

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ipv6/v1alpha1/ipv6range
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    image: linode/alpine3.14
    label: my-linode
    region: us-southeast
    type: g6-nanode-1

---

