apiVersion: volume.linode.upbound.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: volume/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    label: foo-volume
    linodeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foobaz
    region: us-central

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: volume/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: foobaz
  name: foobaz
spec:
  forProvider:
    region: us-west
    rootPassSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    tags:
    - foobaz
    type: g6-nanode-1
