apiVersion: firewall.linode.upbound.io/v1alpha1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: firewall/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: my_firewall
  name: my-firewall
spec:
  forProvider:
    inbound:
    - action: ACCEPT
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      label: allow-http
      ports: "80"
      protocol: TCP
    - action: ACCEPT
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      label: allow-https
      ports: "443"
      protocol: TCP
    inboundPolicy: DROP
    label: my_firewall
    linodesRefs:
    - name: my_instance
    outbound:
    - action: DROP
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      label: reject-http
      ports: "80"
      protocol: TCP
    - action: DROP
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
      label: reject-https
      ports: "443"
      protocol: TCP
    outboundPolicy: ACCEPT

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: firewall/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: my_instance
  name: my-instance
spec:
  forProvider:
    image: linode/ubuntu18.04
    label: my_instance
    region: us-southeast
    rootPassSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    swapSize: 256
    type: g6-standard-1
