/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Config.
func (mg *Config) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromIntPtrValue(mg.Spec.ForProvider.NodebalancerID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.NodebalancerIDRef,
		Selector:     mg.Spec.ForProvider.NodebalancerIDSelector,
		To: reference.To{
			List:    &NodebalancerList{},
			Managed: &Nodebalancer{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NodebalancerID")
	}
	mg.Spec.ForProvider.NodebalancerID = reference.ToIntPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NodebalancerIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Node.
func (mg *Node) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromIntPtrValue(mg.Spec.ForProvider.ConfigID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ConfigIDRef,
		Selector:     mg.Spec.ForProvider.ConfigIDSelector,
		To: reference.To{
			List:    &ConfigList{},
			Managed: &Config{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigID")
	}
	mg.Spec.ForProvider.ConfigID = reference.ToIntPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromIntPtrValue(mg.Spec.ForProvider.NodebalancerID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.NodebalancerIDRef,
		Selector:     mg.Spec.ForProvider.NodebalancerIDSelector,
		To: reference.To{
			List:    &NodebalancerList{},
			Managed: &Nodebalancer{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NodebalancerID")
	}
	mg.Spec.ForProvider.NodebalancerID = reference.ToIntPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NodebalancerIDRef = rsp.ResolvedReference

	return nil
}
