apiVersion: linode.linode.upbound.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: linode/v1alpha1/token
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    expiry: "2100-01-02T03:04:05Z"
    label: token
    scopes: linodes:read_only

---

apiVersion: linode.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: linode/v1alpha1/token
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    provisioner:
      remote-exec:
      - inline: |
          echo -e "[DEFAULT]\n token = ${linode_token.foo.token}\n region=${self.region}\n type=${self.type}" > ~/.linode-cli
          pip install linode-cli
          linode-cli linodes list --format "ipv6,label" --text --no-headers >> /etc/hosts

---

