apiVersion: nodebalancer.linode.upbound.io/v1alpha1
kind: Node
metadata:
  annotations:
    meta.upbound.io/example-id: nodebalancer/v1alpha1/node
  labels:
    testing.upbound.io/example-name: foonode
  name: foonode
spec:
  forProvider:
    address: ${element(linode_instance.web.*.private_ip_address, count.index)}:80
    configIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foofig
    count: "3"
    label: mynodebalancernode
    nodebalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foobar
    weight: 50

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: nodebalancer/v1alpha1/node
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    authorizedKeys:
    - ssh-rsa AAAA...Gw== user@example.local
    count: "3"
    image: linode/ubuntu22.04
    label: web-${count.index + 1}
    privateIp: true
    region: us-east
    rootPassSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    type: g6-standard-1

---

apiVersion: nodebalancer.linode.upbound.io/v1alpha1
kind: Nodebalancer
metadata:
  annotations:
    meta.upbound.io/example-id: nodebalancer/v1alpha1/node
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    clientConnThrottle: 20
    label: mynodebalancer
    region: us-east

---

apiVersion: nodebalancer.linode.upbound.io/v1alpha1
kind: Config
metadata:
  annotations:
    meta.upbound.io/example-id: nodebalancer/v1alpha1/node
  labels:
    testing.upbound.io/example-name: foofig
  name: foofig
spec:
  forProvider:
    algorithm: source
    check: http
    checkAttempts: 3
    checkPath: /foo
    checkTimeout: 30
    nodebalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foobar
    port: 80
    protocol: http
    stickiness: http_cookie
