apiVersion: networking.linode.upbound.io/v1alpha1
kind: IP
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/ip
  labels:
    testing.upbound.io/example-name: test_ip
  name: test-ip
spec:
  forProvider:
    linodeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    public: true
    type: ipv4
