apiVersion: rdns.linode.upbound.io/v1alpha1
kind: RDNS
metadata:
  annotations:
    meta.upbound.io/example-id: rdns/v1alpha1/rdns
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    address: ${linode_instance.foo.ip_address}
    rdns: ${linode_instance.foo.ip_address}.nip.io

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rdns/v1alpha1/rdns
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    image: linode/alpine3.9
    region: ca-east
    type: g6-dedicated-2

---

