/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DevicesInitParameters struct {
}

type DevicesObservation struct {

	// The ID of the underlying entity this device references (i.e. the Linode's ID).
	EntityID *float64 `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// The ID of the Firewall.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// This Firewall's unique label.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The type of Firewall Device.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The URL of the underlying entity this device references.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type DevicesParameters struct {
}

type FirewallInitParameters struct {

	// If true, the Firewall's rules are not enforced (defaults to false).
	// If true, the Firewall is inactive.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// A firewall rule that specifies what inbound network traffic is allowed.
	Inbound []InboundInitParameters `json:"inbound,omitempty" tf:"inbound,omitempty"`

	// The default behavior for inbound traffic. This setting can be overridden by updating the inbound.action property of the Firewall Rule. (ACCEPT, DROP)
	// The default behavior for inbound traffic. This setting can be overridden by updating the inbound.action property for an individual Firewall Rule.
	InboundPolicy *string `json:"inboundPolicy,omitempty" tf:"inbound_policy,omitempty"`

	// This Firewall's unique label.
	// The label for the Firewall. For display purposes only. If no label is provided, a default will be assigned.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// A list of IDs of Linodes this Firewall should govern network traffic for.
	// The IDs of Linodes to apply this firewall to.
	// +crossplane:generate:reference:type=github.com/linode/provider-linode/apis/instance/v1alpha1.Instance
	// +listType=set
	Linodes []*float64 `json:"linodes,omitempty" tf:"linodes,omitempty"`

	// References to Instance in instance to populate linodes.
	// +kubebuilder:validation:Optional
	LinodesRefs []v1.Reference `json:"linodesRefs,omitempty" tf:"-"`

	// Selector for a list of Instance in instance to populate linodes.
	// +kubebuilder:validation:Optional
	LinodesSelector *v1.Selector `json:"linodesSelector,omitempty" tf:"-"`

	// A list of IDs of NodeBalancers this Firewall should govern network traffic for.
	// The IDs of NodeBalancers to apply this firewall to.
	// +listType=set
	Nodebalancers []*float64 `json:"nodebalancers,omitempty" tf:"nodebalancers,omitempty"`

	// A firewall rule that specifies what outbound network traffic is allowed.
	Outbound []OutboundInitParameters `json:"outbound,omitempty" tf:"outbound,omitempty"`

	// The default behavior for outbound traffic. This setting can be overridden by updating the outbound.action property for an individual Firewall Rule. (ACCEPT, DROP)
	// The default behavior for outbound traffic. This setting can be overridden by updating the outbound.action property for an individual Firewall Rule.
	OutboundPolicy *string `json:"outboundPolicy,omitempty" tf:"outbound_policy,omitempty"`

	// A list of tags applied to the Kubernetes cluster. Tags are case-insensitive and are for organizational purposes only.
	// An array of tags applied to this object. Tags are for organizational purposes only.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FirewallObservation struct {

	// When this firewall was created
	Created *string `json:"created,omitempty" tf:"created,omitempty"`

	// The devices associated with this firewall.
	Devices []DevicesObservation `json:"devices,omitempty" tf:"devices,omitempty"`

	// If true, the Firewall's rules are not enforced (defaults to false).
	// If true, the Firewall is inactive.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// The ID of the Firewall.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A firewall rule that specifies what inbound network traffic is allowed.
	Inbound []InboundObservation `json:"inbound,omitempty" tf:"inbound,omitempty"`

	// The default behavior for inbound traffic. This setting can be overridden by updating the inbound.action property of the Firewall Rule. (ACCEPT, DROP)
	// The default behavior for inbound traffic. This setting can be overridden by updating the inbound.action property for an individual Firewall Rule.
	InboundPolicy *string `json:"inboundPolicy,omitempty" tf:"inbound_policy,omitempty"`

	// This Firewall's unique label.
	// The label for the Firewall. For display purposes only. If no label is provided, a default will be assigned.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// A list of IDs of Linodes this Firewall should govern network traffic for.
	// The IDs of Linodes to apply this firewall to.
	// +listType=set
	Linodes []*float64 `json:"linodes,omitempty" tf:"linodes,omitempty"`

	// A list of IDs of NodeBalancers this Firewall should govern network traffic for.
	// The IDs of NodeBalancers to apply this firewall to.
	// +listType=set
	Nodebalancers []*float64 `json:"nodebalancers,omitempty" tf:"nodebalancers,omitempty"`

	// A firewall rule that specifies what outbound network traffic is allowed.
	Outbound []OutboundObservation `json:"outbound,omitempty" tf:"outbound,omitempty"`

	// The default behavior for outbound traffic. This setting can be overridden by updating the outbound.action property for an individual Firewall Rule. (ACCEPT, DROP)
	// The default behavior for outbound traffic. This setting can be overridden by updating the outbound.action property for an individual Firewall Rule.
	OutboundPolicy *string `json:"outboundPolicy,omitempty" tf:"outbound_policy,omitempty"`

	// The status of the Firewall.
	// The status of the firewall.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// A list of tags applied to the Kubernetes cluster. Tags are case-insensitive and are for organizational purposes only.
	// An array of tags applied to this object. Tags are for organizational purposes only.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// When this firewall was last updated
	Updated *string `json:"updated,omitempty" tf:"updated,omitempty"`
}

type FirewallParameters struct {

	// If true, the Firewall's rules are not enforced (defaults to false).
	// If true, the Firewall is inactive.
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// A firewall rule that specifies what inbound network traffic is allowed.
	// +kubebuilder:validation:Optional
	Inbound []InboundParameters `json:"inbound,omitempty" tf:"inbound,omitempty"`

	// The default behavior for inbound traffic. This setting can be overridden by updating the inbound.action property of the Firewall Rule. (ACCEPT, DROP)
	// The default behavior for inbound traffic. This setting can be overridden by updating the inbound.action property for an individual Firewall Rule.
	// +kubebuilder:validation:Optional
	InboundPolicy *string `json:"inboundPolicy,omitempty" tf:"inbound_policy,omitempty"`

	// This Firewall's unique label.
	// The label for the Firewall. For display purposes only. If no label is provided, a default will be assigned.
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// A list of IDs of Linodes this Firewall should govern network traffic for.
	// The IDs of Linodes to apply this firewall to.
	// +crossplane:generate:reference:type=github.com/linode/provider-linode/apis/instance/v1alpha1.Instance
	// +kubebuilder:validation:Optional
	// +listType=set
	Linodes []*float64 `json:"linodes,omitempty" tf:"linodes,omitempty"`

	// References to Instance in instance to populate linodes.
	// +kubebuilder:validation:Optional
	LinodesRefs []v1.Reference `json:"linodesRefs,omitempty" tf:"-"`

	// Selector for a list of Instance in instance to populate linodes.
	// +kubebuilder:validation:Optional
	LinodesSelector *v1.Selector `json:"linodesSelector,omitempty" tf:"-"`

	// A list of IDs of NodeBalancers this Firewall should govern network traffic for.
	// The IDs of NodeBalancers to apply this firewall to.
	// +kubebuilder:validation:Optional
	// +listType=set
	Nodebalancers []*float64 `json:"nodebalancers,omitempty" tf:"nodebalancers,omitempty"`

	// A firewall rule that specifies what outbound network traffic is allowed.
	// +kubebuilder:validation:Optional
	Outbound []OutboundParameters `json:"outbound,omitempty" tf:"outbound,omitempty"`

	// The default behavior for outbound traffic. This setting can be overridden by updating the outbound.action property for an individual Firewall Rule. (ACCEPT, DROP)
	// The default behavior for outbound traffic. This setting can be overridden by updating the outbound.action property for an individual Firewall Rule.
	// +kubebuilder:validation:Optional
	OutboundPolicy *string `json:"outboundPolicy,omitempty" tf:"outbound_policy,omitempty"`

	// A list of tags applied to the Kubernetes cluster. Tags are case-insensitive and are for organizational purposes only.
	// An array of tags applied to this object. Tags are for organizational purposes only.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type InboundInitParameters struct {

	// Controls whether traffic is accepted or dropped by this rule (ACCEPT, DROP). Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	// Controls whether traffic is accepted or dropped by this rule. Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A list of IPv4 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of CIDR blocks or 0.0.0.0/0 (to allow all) this rule applies to.
	IPv4 []*string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// A list of IPv6 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of IPv6 addresses or networks this rule applies to.
	IPv6 []*string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// This Firewall's unique label.
	// Used to identify this rule. For display purposes only.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	Ports *string `json:"ports,omitempty" tf:"ports,omitempty"`

	// The network protocol this rule controls. (TCP, UDP, ICMP)
	// The network protocol this rule controls.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type InboundObservation struct {

	// Controls whether traffic is accepted or dropped by this rule (ACCEPT, DROP). Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	// Controls whether traffic is accepted or dropped by this rule. Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A list of IPv4 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of CIDR blocks or 0.0.0.0/0 (to allow all) this rule applies to.
	IPv4 []*string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// A list of IPv6 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of IPv6 addresses or networks this rule applies to.
	IPv6 []*string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// This Firewall's unique label.
	// Used to identify this rule. For display purposes only.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	Ports *string `json:"ports,omitempty" tf:"ports,omitempty"`

	// The network protocol this rule controls. (TCP, UDP, ICMP)
	// The network protocol this rule controls.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type InboundParameters struct {

	// Controls whether traffic is accepted or dropped by this rule (ACCEPT, DROP). Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	// Controls whether traffic is accepted or dropped by this rule. Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	// +kubebuilder:validation:Optional
	Action *string `json:"action" tf:"action,omitempty"`

	// A list of IPv4 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of CIDR blocks or 0.0.0.0/0 (to allow all) this rule applies to.
	// +kubebuilder:validation:Optional
	IPv4 []*string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// A list of IPv6 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of IPv6 addresses or networks this rule applies to.
	// +kubebuilder:validation:Optional
	IPv6 []*string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// This Firewall's unique label.
	// Used to identify this rule. For display purposes only.
	// +kubebuilder:validation:Optional
	Label *string `json:"label" tf:"label,omitempty"`

	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	// +kubebuilder:validation:Optional
	Ports *string `json:"ports,omitempty" tf:"ports,omitempty"`

	// The network protocol this rule controls. (TCP, UDP, ICMP)
	// The network protocol this rule controls.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`
}

type OutboundInitParameters struct {

	// Controls whether traffic is accepted or dropped by this rule (ACCEPT, DROP). Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	// Controls whether traffic is accepted or dropped by this rule. Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A list of IPv4 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of CIDR blocks or 0.0.0.0/0 (to allow all) this rule applies to.
	IPv4 []*string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// A list of IPv6 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of IPv6 addresses or networks this rule applies to.
	IPv6 []*string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// This Firewall's unique label.
	// Used to identify this rule. For display purposes only.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	Ports *string `json:"ports,omitempty" tf:"ports,omitempty"`

	// The network protocol this rule controls. (TCP, UDP, ICMP)
	// The network protocol this rule controls.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type OutboundObservation struct {

	// Controls whether traffic is accepted or dropped by this rule (ACCEPT, DROP). Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	// Controls whether traffic is accepted or dropped by this rule. Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A list of IPv4 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of CIDR blocks or 0.0.0.0/0 (to allow all) this rule applies to.
	IPv4 []*string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// A list of IPv6 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of IPv6 addresses or networks this rule applies to.
	IPv6 []*string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// This Firewall's unique label.
	// Used to identify this rule. For display purposes only.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	Ports *string `json:"ports,omitempty" tf:"ports,omitempty"`

	// The network protocol this rule controls. (TCP, UDP, ICMP)
	// The network protocol this rule controls.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type OutboundParameters struct {

	// Controls whether traffic is accepted or dropped by this rule (ACCEPT, DROP). Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	// Controls whether traffic is accepted or dropped by this rule. Overrides the Firewall’s inbound_policy if this is an inbound rule, or the outbound_policy if this is an outbound rule.
	// +kubebuilder:validation:Optional
	Action *string `json:"action" tf:"action,omitempty"`

	// A list of IPv4 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of CIDR blocks or 0.0.0.0/0 (to allow all) this rule applies to.
	// +kubebuilder:validation:Optional
	IPv4 []*string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// A list of IPv6 addresses or networks. Must be in IP/mask (CIDR) format.
	// A list of IPv6 addresses or networks this rule applies to.
	// +kubebuilder:validation:Optional
	IPv6 []*string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// This Firewall's unique label.
	// Used to identify this rule. For display purposes only.
	// +kubebuilder:validation:Optional
	Label *string `json:"label" tf:"label,omitempty"`

	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	// A string representation of ports and/or port ranges (i.e. "443" or "80-90, 91").
	// +kubebuilder:validation:Optional
	Ports *string `json:"ports,omitempty" tf:"ports,omitempty"`

	// The network protocol this rule controls. (TCP, UDP, ICMP)
	// The network protocol this rule controls.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`
}

// FirewallSpec defines the desired state of Firewall
type FirewallSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FirewallParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FirewallInitParameters `json:"initProvider,omitempty"`
}

// FirewallStatus defines the observed state of Firewall.
type FirewallStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FirewallObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Firewall is the Schema for the Firewalls API. Manages a Linode Firewall.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,linode}
type Firewall struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.inboundPolicy) || (has(self.initProvider) && has(self.initProvider.inboundPolicy))",message="spec.forProvider.inboundPolicy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.label) || (has(self.initProvider) && has(self.initProvider.label))",message="spec.forProvider.label is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.outboundPolicy) || (has(self.initProvider) && has(self.initProvider.outboundPolicy))",message="spec.forProvider.outboundPolicy is a required parameter"
	Spec   FirewallSpec   `json:"spec"`
	Status FirewallStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FirewallList contains a list of Firewalls
type FirewallList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Firewall `json:"items"`
}

// Repository type metadata.
var (
	Firewall_Kind             = "Firewall"
	Firewall_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Firewall_Kind}.String()
	Firewall_KindAPIVersion   = Firewall_Kind + "." + CRDGroupVersion.String()
	Firewall_GroupVersionKind = CRDGroupVersion.WithKind(Firewall_Kind)
)

func init() {
	SchemeBuilder.Register(&Firewall{}, &FirewallList{})
}
