//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementGroupAssignment) DeepCopyInto(out *PlacementGroupAssignment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementGroupAssignment.
func (in *PlacementGroupAssignment) DeepCopy() *PlacementGroupAssignment {
	if in == nil {
		return nil
	}
	out := new(PlacementGroupAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementGroupAssignment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementGroupAssignmentInitParameters) DeepCopyInto(out *PlacementGroupAssignmentInitParameters) {
	*out = *in
	if in.CompliantOnly != nil {
		in, out := &in.CompliantOnly, &out.CompliantOnly
		*out = new(bool)
		**out = **in
	}
	if in.LinodeID != nil {
		in, out := &in.LinodeID, &out.LinodeID
		*out = new(float64)
		**out = **in
	}
	if in.LinodeIDRef != nil {
		in, out := &in.LinodeIDRef, &out.LinodeIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LinodeIDSelector != nil {
		in, out := &in.LinodeIDSelector, &out.LinodeIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PlacementGroupID != nil {
		in, out := &in.PlacementGroupID, &out.PlacementGroupID
		*out = new(float64)
		**out = **in
	}
	if in.PlacementGroupIDRef != nil {
		in, out := &in.PlacementGroupIDRef, &out.PlacementGroupIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.PlacementGroupIDSelector != nil {
		in, out := &in.PlacementGroupIDSelector, &out.PlacementGroupIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementGroupAssignmentInitParameters.
func (in *PlacementGroupAssignmentInitParameters) DeepCopy() *PlacementGroupAssignmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(PlacementGroupAssignmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementGroupAssignmentList) DeepCopyInto(out *PlacementGroupAssignmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlacementGroupAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementGroupAssignmentList.
func (in *PlacementGroupAssignmentList) DeepCopy() *PlacementGroupAssignmentList {
	if in == nil {
		return nil
	}
	out := new(PlacementGroupAssignmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementGroupAssignmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementGroupAssignmentObservation) DeepCopyInto(out *PlacementGroupAssignmentObservation) {
	*out = *in
	if in.CompliantOnly != nil {
		in, out := &in.CompliantOnly, &out.CompliantOnly
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LinodeID != nil {
		in, out := &in.LinodeID, &out.LinodeID
		*out = new(float64)
		**out = **in
	}
	if in.PlacementGroupID != nil {
		in, out := &in.PlacementGroupID, &out.PlacementGroupID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementGroupAssignmentObservation.
func (in *PlacementGroupAssignmentObservation) DeepCopy() *PlacementGroupAssignmentObservation {
	if in == nil {
		return nil
	}
	out := new(PlacementGroupAssignmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementGroupAssignmentParameters) DeepCopyInto(out *PlacementGroupAssignmentParameters) {
	*out = *in
	if in.CompliantOnly != nil {
		in, out := &in.CompliantOnly, &out.CompliantOnly
		*out = new(bool)
		**out = **in
	}
	if in.LinodeID != nil {
		in, out := &in.LinodeID, &out.LinodeID
		*out = new(float64)
		**out = **in
	}
	if in.LinodeIDRef != nil {
		in, out := &in.LinodeIDRef, &out.LinodeIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.LinodeIDSelector != nil {
		in, out := &in.LinodeIDSelector, &out.LinodeIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PlacementGroupID != nil {
		in, out := &in.PlacementGroupID, &out.PlacementGroupID
		*out = new(float64)
		**out = **in
	}
	if in.PlacementGroupIDRef != nil {
		in, out := &in.PlacementGroupIDRef, &out.PlacementGroupIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.PlacementGroupIDSelector != nil {
		in, out := &in.PlacementGroupIDSelector, &out.PlacementGroupIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementGroupAssignmentParameters.
func (in *PlacementGroupAssignmentParameters) DeepCopy() *PlacementGroupAssignmentParameters {
	if in == nil {
		return nil
	}
	out := new(PlacementGroupAssignmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementGroupAssignmentSpec) DeepCopyInto(out *PlacementGroupAssignmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementGroupAssignmentSpec.
func (in *PlacementGroupAssignmentSpec) DeepCopy() *PlacementGroupAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementGroupAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementGroupAssignmentStatus) DeepCopyInto(out *PlacementGroupAssignmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementGroupAssignmentStatus.
func (in *PlacementGroupAssignmentStatus) DeepCopy() *PlacementGroupAssignmentStatus {
	if in == nil {
		return nil
	}
	out := new(PlacementGroupAssignmentStatus)
	in.DeepCopyInto(out)
	return out
}
