/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	_v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BucketAccessObservation struct {
}

type BucketAccessParameters struct {

	// The unique label of the bucket to which the key will grant limited access.
	// The unique label of the bucket to which the key will grant limited access.
	// +kubebuilder:validation:Required
	BucketName *string `json:"bucketName" tf:"bucket_name,omitempty"`

	// The Object Storage cluster where a bucket to which the key is granting access is hosted.
	// The Object Storage cluster where a bucket to which the key is granting access is hosted.
	// +kubebuilder:validation:Required
	Cluster *string `json:"cluster" tf:"cluster,omitempty"`

	// This Limited Access Key’s permissions for the selected bucket. Changing  (read_write, read_only)
	// This Limited Access Key’s permissions for the selected bucket.
	// +kubebuilder:validation:Required
	Permissions *string `json:"permissions" tf:"permissions,omitempty"`
}

type StorageKeyObservation struct {

	// This keypair's access key. This is not secret.
	// This keypair's access key. This is not secret.
	AccessKey *string `json:"accessKey,omitempty" tf:"access_key,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether or not this key is a limited access key.
	// Whether or not this key is a limited access key.
	Limited *bool `json:"limited,omitempty" tf:"limited,omitempty"`
}

type StorageKeyParameters struct {

	// Defines this key as a Limited Access Key. Limited Access Keys restrict this Object Storage key’s access to only the bucket(s) declared in this array and define their bucket-level permissions. Not providing this block will not limit this Object Storage Key.
	// A list of permissions to grant this limited access key.
	// +kubebuilder:validation:Optional
	BucketAccess []BucketAccessParameters `json:"bucketAccess,omitempty" tf:"bucket_access,omitempty"`

	// The label given to this key. For display purposes only.
	// The label given to this key. For display purposes only.
	// +kubebuilder:validation:Required
	Label *string `json:"label" tf:"label,omitempty"`
}

// StorageKeySpec defines the desired state of StorageKey
type StorageKeySpec struct {
	_v1.ResourceSpec `json:",inline"`
	ForProvider      StorageKeyParameters `json:"forProvider"`
}

// StorageKeyStatus defines the observed state of StorageKey.
type StorageKeyStatus struct {
	_v1.ResourceStatus `json:",inline"`
	AtProvider         StorageKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// StorageKey is the Schema for the StorageKeys API. Manages a Linode Object Storage Key.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,linode}
type StorageKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              StorageKeySpec   `json:"spec"`
	Status            StorageKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StorageKeyList contains a list of StorageKeys
type StorageKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StorageKey `json:"items"`
}

// Repository type metadata.
var (
	StorageKey_Kind             = "StorageKey"
	StorageKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StorageKey_Kind}.String()
	StorageKey_KindAPIVersion   = StorageKey_Kind + "." + CRDGroupVersion.String()
	StorageKey_GroupVersionKind = CRDGroupVersion.WithKind(StorageKey_Kind)
)

func init() {
	SchemeBuilder.Register(&StorageKey{}, &StorageKeyList{})
}
