apiVersion: objectstorage.linode.upbound.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    label: mybucket
    region: us-mia
