apiVersion: objectstorage.linode.upbound.io/v1alpha1
kind: Object
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/object
  labels:
    testing.upbound.io/example-name: object
  name: object
spec:
  forProvider:
    accessKeySelector:
      matchLabels:
        testing.upbound.io/example-name: my_key
    bucket: my-bucket
    key: my-object
    region: us-mia
    secretKeySecretRef:
      key: attribute.secret_key
      name: example-object-storage-key
      namespace: upbound-system
    source: ${pathexpand("~/files/log.txt")}
