apiVersion: sshkey.linode.upbound.io/v1alpha1
kind: SSHKey
metadata:
  annotations:
    meta.upbound.io/example-id: sshkey/v1alpha1/sshkey
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    label: foo
    sshKey: ${chomp(file("~/.ssh/id_rsa.pub"))}

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: sshkey/v1alpha1/sshkey
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    authorizedKeys:
    - ${linode_sshkey.foo.ssh_key}
    image: linode/ubuntu18.04
    label: foo
    region: us-east
    rootPassSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    type: g6-nanode-1
