apiVersion: domain.linode.upbound.io/v1alpha1
kind: Record
metadata:
  annotations:
    meta.upbound.io/example-id: domain/v1alpha1/record
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    domainIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foobar
    name: www
    recordType: CNAME
    target: foobar.example
