apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    authorizedKeys:
    - ssh-rsa AAAA...Gw== user@example.local
    image: linode/ubuntu22.04
    label: simple_instance
    privateIp: true
    region: us-central
    rootPassSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    swapSize: 256
    tags:
    - foo
    type: g6-standard-1
