apiVersion: instance.linode.upbound.io/v1alpha1
kind: IP
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/ip
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    linodeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    public: true

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/ip
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    image: linode/alpine3.12
    label: foobar-test
    region: us-east
    type: g6-nanode-1

---

