apiVersion: image.linode.upbound.io/v1alpha1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: image/v1alpha1/image
  labels:
    testing.upbound.io/example-name: bar
  name: bar
spec:
  forProvider:
    description: Image taken from foo
    diskIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    label: foo-sda-image
    linodeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: image/v1alpha1/image
  labels:
    testing.upbound.io/example-name: bar_based
  name: bar-based
spec:
  forProvider:
    image: ${linode_image.bar.id}
    region: eu-west
    type: g6-nanode-1

---

apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: image/v1alpha1/image
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    image: linode/ubuntu22.04
    region: us-central
    rootPassSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    type: g6-nanode-1

---

